// import logo from './logo.svg';
import '../App.css';
import React from 'react'; 
import { useState, useEffect } from 'react';
import Navbar from './Navbar';
import { Button, ThemeProvider, Frame } from '@react95/core'
import TicketCard from './TicketCard';
import Board from './Board';
import { BrowserRouter as Router, Routes, Route, Redirect} from 'react-router-dom';



function PrivacyPage() {
  
 

  return (
    <ThemeProvider>
    <div className="App" id="outer-container">
      <div id="page-wrap">
      <Navbar></Navbar>
      <Frame padding={4} className='privacy__outer'>
        <Frame boxShadow="in" className='privacy__inner'>
          <h1>Privacy Policy</h1>
          <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.

We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Free Privacy Policy Generator.</p>

          <h1>Interpretation and Definitions</h1>
          <h2>Interpretation</h2>
          <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.

</p>
          <h2>Definitions</h2>
          <p>For the purposes of this Privacy Policy:

</p>
          <ul>
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li>Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Backend Boyz LLC, 1 Oslovägen, Oslo 13337.

</li>
<li>Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.

</li>
<li>Country refers to: Norway

</li>
<li>Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.

</li>
<li>Personal Data is any information that relates to an identified or identifiable individual.

</li>
<li>Service refers to the Website.

</li>
<li>Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.

</li>
<li>Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).

</li>
<li>Website refers to Fabryca, accessible from https://www.fabryca.no

</li>
<li>You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.

</li>
          </ul>
        </Frame>
      </Frame>
      </div>
    </div>
    </ThemeProvider>
  );
}

export default PrivacyPage;